name: Deploy Docs On Publish

on:
    release:
        types:
            - published
    workflow_dispatch:

jobs:
    build-and-deploy:
        name: Deploy Docs to gh-pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
            - name: Add TypeScript problem matcher
              run: echo "::add-matcher::.github/problemMatchers/tsc.json"
            - name: Use Node.js v20
              uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
              with:
                  node-version: 20
                  cache: yarn
                  registry-url: https://registry.yarnpkg.com/
            - name: Install Dependencies
              uses: ./scripts/yarnCache
            - name: Build all packages
              run: yarn build
            - name: Generate Docs
              run: yarn docs
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@881db5376404c5c8d621010bcbec0310b58d5e29 # v4.6.8
              with:
                  branch: gh-pages
                  folder: docs
